### ISSUE TITLE
Sharing Method - Virtual Camera

### ISSUE THREAD

**Issue by JoelMon** [mjacobus/jw-play#26]
By any chance, will the prototype have virtual camera capability using [v4l2loopback](https://arcoresearchgroup.wordpress.com/2020/06/02/virtual-camera-for-opencv-using-v4l2loopback/)? I love how I can share photos and video via OBS using v4l2loopback but OBS can be a bit wonky when you have a lot of videos (ASL congregation) and pictures during a talk.

Just curious,
Joel M. :smiley:

**Comment by mjacobus** [comment]
Hey @JoelMon 

Until 5 seconds ago I had not even heard of v4l2loopback 😄 . So that is not on my radar yet. And know I will not have time anytime soon to even consider that, but feel free to expand on how that could fit in the prototype and you are more then welcome to PR it :)

**Comment by JoelMon** [comment]
I've never played with Ruby before but I'll look into it. Perhaps I can write up a doc outlining the V4L2Loopback kernel module and then experiment.

**Comment by JoelMon** [comment]
I made a new issue with more information about v4l2loopback. Issue #27.

**Comment by mjacobus** [comment]
> I've never played with Ruby before but I'll look into it. Perhaps I can write up a doc outlining the V4L2Loopback kernel module and then experiment.

This project is pure javascript/html/css running on electron :)

> I made a new issue with more information about v4l2loopback. Issue #27.

Thank you @JoelMon ❤️  I will close this issue in favor of the one very well described you created.
