### ISSUE TITLE
Installaction Package

### ISSUE THREAD

**Issue by andryeltj** [mjacobus/jw-play#28]
One idea.
If you, Brother, pack its in AppImage and .deb.

Good App.

**Comment by mjacobus** [comment]
Hey @andryeltj. 

That is a great idea. However, I lack the time to learn how to do that, at the moment.

Do you know how to achieve that? Feel free to create a PR.
This app uses electron, and [these](https://www.electronjs.org/docs/tutorial/application-distribution) are the packaging instructions

**Comment by JoelMon** [comment]
@andryeltj, here's a [walk through for using electron-builder](https://medium.com/how-to-electron/a-complete-guide-to-packaging-your-electron-app-1bdc717d739f).

I might take a try at it but can't at the moment. :wave:

**Comment by JoelMon** [comment]
Quick update,

Github actions makes creating packages simple and covenant. Basicly you spin up any number of docker images {Linux, MacOSX, Windows} and run scripts to build and release packages.

Here's an example in one of my projects where an Ubuntu deb file is created and added to the releases. 
https://github.com/JoelMon/scriptx/blob/main/.github/workflows/make-deb.yml

**Comment by mjacobus** [comment]
Awesome! I have to buy some time and hook this action. Thank you @JoelMon ❤️

**Comment by mjacobus** [comment]
Hey  @andryeltj 👋🏻 

You can find both AppImage and deb packages [here](https://github.com/mjacobus/jw-play/releases/latest).
